/* ============================================================
   tools/build_question_bank.js

   Pulls every question and answer out of course-questions.html
   into bio005-question-bank.js, so Hootie can answer from the
   same 248 answers the page shows rather than shrugging.

   The page stays the source of truth. Edit a question there and
   re-run this. Never hand edit the generated file.

   Run: node tools/build_question_bank.js
   ============================================================ */
const fs = require('fs');

const html = fs.readFileSync('course-questions.html', 'utf8');
const out = [];

// each entry is <details class="qa" id="qN"><summary>Q</summary><div class="ans">A</div></details>
const re = /<details class="qa" id="(q\d+)"><summary>([\s\S]*?)<\/summary><div class="ans">([\s\S]*?)<\/div><\/details>/g;
let m;
while ((m = re.exec(html)) !== null) {
  const id = m[1];
  const q = m[2].replace(/<[^>]+>/g, '').replace(/&middot;/g, '·').replace(/&amp;/g, '&')
                .replace(/&quot;/g, '"').replace(/&#39;/g, "'").replace(/\s+/g, ' ').trim();
  // the answer keeps its links: they are the useful half of most answers
  const a = m[3].replace(/\s+/g, ' ').trim();
  if (q && a) out.push({ id, q, a });
}

// section headings give each question a topic, which makes a near miss useful
const sections = [];
const sre = /<h2[^>]*id="([^"]+)"[^>]*>([\s\S]*?)<\/h2>/g;
let s;
while ((s = sre.exec(html)) !== null) {
  sections.push({ at: s.index, name: s[2].replace(/<[^>]+>/g, '').replace(/\s+/g, ' ').trim() });
}
out.forEach(e => {
  const at = html.indexOf('id="' + e.id + '"');
  let name = '';
  sections.forEach(sec => { if (sec.at < at) name = sec.name; });
  e.topic = name;
});

const banner = `/* ============================================================
   BIO 005 Human Physiology, Fall 2026
   bio005-question-bank.js

   GENERATED by tools/build_question_bank.js from
   course-questions.html. Do not hand edit: edit the page and
   re-run the script.

   ${out.length} questions with their answers, so Hootie answers from
   the same bank the students read rather than saying it does not
   know something that is already written down.
   ============================================================ */
`;
fs.writeFileSync('bio005-question-bank.js',
  banner + 'window.BIO005_QUESTIONS = ' + JSON.stringify(out, null, 1) + ';\n');

console.log('extracted ' + out.length + ' questions');
const topics = {};
out.forEach(e => topics[e.topic] = (topics[e.topic] || 0) + 1);
Object.keys(topics).forEach(t => console.log('  ' + String(topics[t]).padStart(4) + '  ' + (t || '(no section)')));
