/* ============================================================
   tools/gen_competency_pages.js

   Builds week-NN-competencies.html for weeks 2 to 15 from the two
   sources of record: bio005-competencies.js for which competencies a
   week carries and how they group, assets/bio005-sheet-data.js for the
   two brain dump prompts under each one.

   The prompts are ON the page now. Scrubs, Sep 7 2026: "too much
   jumping around." A student picks A or B here, sees the tick stay,
   and builds the note sheet from the same page they read the
   competency on.

   Week 1 is hand built and is NOT regenerated by this script.

   Run: node tools/gen_competency_pages.js
   ============================================================ */
const fs = require('fs'), path = require('path');
const ROOT = process.cwd();
global.window = {};
require(path.join(ROOT, 'bio005-competencies.js'));
require(path.join(ROOT, 'assets/bio005-sheet-data.js'));
require(path.join(ROOT, 'bio005-schedule-fall2026.js'));
const C = window.BIO005_COMPETENCIES, SHEET = window.BIO005_SHEET, WEEKS = window.BIO005_WEEKS;

const esc = s => String(s == null ? '' : s)
  .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
  .replace(/"/g, '&quot;').replace(/'/g, '&#39;');

const PART = { 1: 'Part 1', 2: 'Part 2', 3: 'Part 3' };
const LONG = d => {
  const [y, m, dd] = d.split('-').map(Number);
  return new Date(Date.UTC(y, m - 1, dd)).toLocaleDateString('en-US',
    { weekday: 'long', month: 'long', day: 'numeric', timeZone: 'UTC' });
};

function page(w) {
  const wk = WEEKS.find(x => x.wk === w);
  const items = (SHEET[String(w)] || {}).items || [];
  const comps = C.filter(c => c.week === w);
  const n = items.length;

  // group by the body-system tag the map already carries, in first-seen order
  const order = [], byGen = {};
  comps.forEach(c => { if (!byGen[c.general]) { byGen[c.general] = []; order.push(c.general); }
                       byGen[c.general].push(c); });

  let idx = 0, groups = '';
  order.forEach(g => {
    var cnt = byGen[g].length;
    groups += '\n  <div class="chead"><span class="cl">' + cnt + (cnt === 1 ? ' competency' : ' competencies') + '</span>'
           +  '<h2>' + esc(g) + '</h2></div>\n';
    byGen[g].forEach(c => {
      idx++;
      const it = items.find(i => i.name === c.name) || {};
      const id = c.id;
      const lab = (c.facets || []).indexOf('lab') > -1;
      const rows = ['a', 'b'].map(L => {
        const txt = (it[L] || '').trim();
        if (!txt) return '';
        return '\n      <div class="prompt" data-c="' + esc(id) + '" data-l="' + L + '">'
             + '<input type="checkbox" id="' + esc(id) + '-' + L + '">'
             + '<label for="' + esc(id) + '-' + L + '">'
             + '<span class="plet">' + L.toUpperCase() + '</span>' + esc(txt) + '</label></div>';
      }).join('');
      const pick = rows
        ? '\n      <p class="pick">Pick one and do that one</p>' + rows
        : '\n      <p class="pick pending">Prompts post when the week opens</p>';
      groups +=
        '  <section class="comp" id="c-' + esc(id) + '" aria-labelledby="h-' + esc(id) + '">\n'
      + '      <div class="chd"><span class="cnum">' + idx + '</span>'
      + '<h3 class="cname" id="h-' + esc(id) + '">' + esc(c.name) + '</h3>'
      + '<span class="tag">Lecture</span>' + (lab ? '<span class="tag lab">Lab</span>' : '') + '</div>\n'
      + '      <p class="can"><span class="canlab">You should be able to</span>' + esc(c.can) + '</p>'
      + pick + '\n  </section>\n';
    });
  });

  const jumps = [['N','j-note','note-sheet.html?week=','note sheet'],
                 ['P','j-prob','assignment-bookproblems.html?week=','problems'],
                 ['L','j-lab','assignment-physioex.html?week=','lab'],
                 ['D','j-disc','assignment-discussion.html?week=','discussion'],
                 ['S','j-study','mastery-physio-os-standalone.html?week=','study session']]
    .map(j => '    <li><a class="' + j[1] + '" href="' + j[2] + w + '" target="_top" title="Week '
      + w + ' ' + j[3] + '">' + j[0] + '<span class="mm-vh">Week ' + w + ' ' + j[3] + '</span></a></li>')
    .join('\n');

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Week ${w} competencies &middot; BIO 005 Human Physiology</title>
<link rel="icon" type="image/svg+xml" href="icon.svg">
<link rel="stylesheet" href="assets/fonts-site.css">
<link rel="stylesheet" href="assets/brandbar.css">
<style>
:root{
  --navy:#0B1530; --navy-deep:#060A18; --tint:#ECEFF4;
  --gold:#C9A14A; --gold-deep:#8A6D33;
  --maroon:#8B3A2E; --maroon-dk:#6E2D24;
  --page:#FAFAF9; --card:#FFFFFF;
  --muted:#414B5C; --faint:#5A6675; --rule:rgba(11,21,48,.16);
  --display:'Open Sans',system-ui,-apple-system,'Segoe UI',Helvetica,Arial,sans-serif;
  --body:'Plus Jakarta Sans',system-ui,-apple-system,'Segoe UI',Helvetica,Arial,sans-serif;
}
*,*::before,*::after{box-sizing:border-box}
html,body{margin:0}
body{font-family:var(--body);background:var(--page);color:var(--navy);font-size:16px;
  line-height:1.65;-webkit-font-smoothing:antialiased}
h1,h2,h3{font-family:var(--display);font-weight:800;letter-spacing:-.022em;margin:0}
p{margin:0 0 14px;max-width:70ch}
a{color:var(--maroon);text-underline-offset:3px}
a:hover{color:var(--maroon-dk)}
:focus-visible{outline:3px solid var(--maroon);outline-offset:3px;border-radius:3px}
.wrap{max-width:1000px;margin:0 auto;padding:0 20px}
.skip{position:absolute;left:-9999px;top:0;z-index:90;background:var(--navy);color:#fff;
  padding:12px 18px;font-weight:700;text-decoration:none}
.skip:focus{left:0;top:0}

/* light page, maroon eyebrow, two tone headline. No dark band. */
header.top{padding:30px 0 24px}
header.top .eyebrow{font-size:11px;font-weight:700;letter-spacing:.26em;text-transform:uppercase;
  color:var(--maroon);margin:0 0 10px}
header.top h1{font-size:clamp(26px,4.4vw,38px);line-height:1.14;color:var(--navy);max-width:24ch}
header.top h1 b{color:var(--maroon);font-weight:800}
header.top p.sub{color:var(--muted);margin:12px 0 0;font-size:16px}

.homebar{max-width:1000px;margin:0 auto;padding:16px 20px 0}
.home{display:inline-flex;align-items:center;gap:8px;background:var(--navy);color:#fff;
  text-decoration:none;font-weight:700;font-size:14.5px;border-radius:8px;padding:9px 15px;
  transition:background 160ms ease}
.home:hover{background:var(--maroon);color:#fff}

.pwrap{background:var(--card);border:1px solid var(--rule);border-radius:10px;
  padding:16px 20px;margin:22px 0 0}
.pbar{height:9px;background:var(--tint);border-radius:99px;overflow:hidden;margin-top:9px}
.pfill{height:100%;width:0;background:var(--maroon);border-radius:99px;transition:width 260ms ease}
.pnote{font-size:12.5px;color:var(--muted);margin:7px 0 0}

main{padding:8px 0 60px}
.chead{border-left:4px solid var(--maroon);padding:2px 0 2px 16px;margin:32px 0 6px}
.chead .cl{font-size:11px;font-weight:700;letter-spacing:.24em;text-transform:uppercase;
  color:var(--maroon);display:block;margin-bottom:4px}
.chead h2{font-size:21px;color:var(--maroon)}

.comp{background:var(--card);border:1px solid var(--rule);border-radius:10px;
  padding:18px 20px;margin:12px 0;break-inside:avoid}
.comp.done{background:var(--tint);border-color:var(--maroon)}
.chd{display:flex;gap:11px;align-items:baseline;flex-wrap:wrap}
.cnum{font-family:var(--display);font-weight:800;font-size:14px;color:var(--maroon);
  white-space:nowrap;font-variant-numeric:tabular-nums}
.cname{font-family:var(--display);font-weight:800;font-size:17.5px;letter-spacing:-.02em}
.tag{font-size:10px;font-weight:700;letter-spacing:.14em;text-transform:uppercase;
  border:1px solid var(--rule);border-radius:99px;padding:2px 9px;color:var(--faint);white-space:nowrap}
.tag.lab{color:var(--maroon);border-color:var(--maroon)}
.can{font-size:15px;color:var(--navy);margin:9px 0 0}
.canlab{font-size:10px;font-weight:700;letter-spacing:.2em;text-transform:uppercase;
  color:var(--faint);display:block;margin-bottom:3px}
.pick{font-size:12.5px;font-weight:700;letter-spacing:.14em;text-transform:uppercase;
  color:var(--faint);margin:16px 0 8px}
.pick.pending{color:#5F4514}
.prompt{display:flex;gap:11px;align-items:flex-start;padding:11px 13px;
  border:1px solid var(--rule);border-radius:7px;margin:0 0 8px;background:var(--card)}
.prompt:last-child{margin-bottom:0}
.prompt input[type=checkbox]{flex:0 0 auto;width:22px;height:22px;margin:1px 0 0;
  accent-color:var(--maroon);cursor:pointer}
.prompt label{cursor:pointer;margin:0;font-size:14.5px}
.prompt.checked{background:var(--tint);border-color:var(--maroon)}
.plet{font-family:var(--display);font-weight:800;color:var(--maroon-dk);margin-right:7px}

.foot{margin:40px 0 0;padding-top:18px;border-top:1px solid var(--rule);
  display:flex;justify-content:space-between;gap:14px;flex-wrap:wrap;
  font-size:13px;color:var(--muted)}

@media (prefers-reduced-motion:reduce){*{transition:none!important;animation:none!important}}
@media print{
  .mm-brandbar,.mm-jumpwrap,.homebar,.pwrap,.skip{display:none!important}
  body{background:#fff;font-size:10.5pt}
  .comp{break-inside:avoid;border-color:#999}

}
</style>
</head>
<body>
<a class="skip" href="#main">Skip to the competencies</a>

<div class="mm-brandbar"><div class="mm-wrap">
  <a class="mm-mark" href="course-start.html" target="_top">
    <svg viewBox="40 10 125 148" width="22" height="26" role="img" aria-label="BIO 005 Human Physiology, course home">
      <g transform="translate(0,18)">
        <g transform="translate(60,0) rotate(8 0 130)"><circle cx="0" cy="20" r="10" fill="#0B1530"/><path d="M 0,32 C -10,32 -16,36 -16,42 C -16,55 -13,68 -11,82 C -10,100 -12,118 -14,130 L 14,130 C 12,118 10,100 11,82 C 13,68 16,55 16,42 C 16,36 10,32 0,32 Z" fill="#0B1530"/></g>
        <g transform="translate(100,0)"><circle cx="0" cy="10" r="11" fill="#8B3A2E"/><path d="M 0,22 C -11,22 -17,26 -17,34 C -17,52 -14,70 -12,86 C -11,108 -13,122 -15,132 L 15,132 C 13,122 11,108 12,86 C 14,70 17,52 17,34 C 17,26 11,22 0,22 Z" fill="#8B3A2E"/></g>
        <g transform="translate(140,0) rotate(-8 0 130)"><circle cx="0" cy="20" r="10" fill="#C9A14A"/><path d="M 0,32 C -10,32 -16,36 -16,42 C -16,55 -13,68 -11,82 C -10,100 -12,118 -14,130 L 14,130 C 12,118 10,100 11,82 C 13,68 16,55 16,42 C 16,36 10,32 0,32 Z" fill="#C9A14A"/></g>
      </g>
    </svg>
    <span class="mm-wm">BIO <b>005</b><span class="mm-wmsub">Human Physiology</span></span>
  </a>
  <span class="mm-course">BIO 005 &middot; Fall 2026</span>
</div></div>

<div class="homebar"><a class="home" href="course-start.html" target="_top">
  <span aria-hidden="true">&larr;</span> Course home</a></div>

<div class="mm-jumpwrap">
  <span class="lbl">Week ${w}</span>
  <ul class="mm-jump">
${jumps}
  </ul>
</div>

<header class="top"><div class="wrap">
  <p class="eyebrow">BIO 005 &middot; Week ${w} &middot; ${PART[wk.module]}</p>
  <h1>Everything Week ${w} <b>asks you to be able to do.</b></h1>
  <p class="sub">${esc(wk.title)}. ${n} ${n === 1 ? 'competency' : 'competencies'}, each one a single thing you will be able to do by ${LONG(wk.closes)}.</p>
</div></header>

<div class="wrap">
  <div class="pwrap">
    <p style="margin:0;font-size:14px"><strong id="pcount">0 of ${n}</strong> picked</p>
    <div class="pbar" role="progressbar" aria-labelledby="pcount" aria-valuemin="0" aria-valuemax="${n}" aria-valuenow="0"><div class="pfill" id="pfill"></div></div>
    <p class="pnote">Tick the prompt you are going to do for each competency. Your ticks stay on this device, so you can come back to the same list.</p>
  </div>
</div>

<main id="main"><div class="wrap">
${groups}
  <p class="foot"><span>BIO 005 Human Physiology &middot; Yuba College &middot; Fall 2026</span><span>Dr. Sharilyn Rennie</span></p>
</div></main>

<script>
(function(){
  var KEY = 'bio005-comp-week-${w}';
  var state = {};
  try { state = JSON.parse(localStorage.getItem(KEY) || '{}') || {}; } catch(e) { state = {}; }

  var rows = [].slice.call(document.querySelectorAll('.prompt'));
  var total = ${n};

  function paint(){
    var picked = 0, seen = {};
    rows.forEach(function(r){
      var c = r.getAttribute('data-c'), l = r.getAttribute('data-l');
      var on = state[c] === l;
      r.classList.toggle('checked', on);
      r.querySelector('input').checked = on;
      var comp = document.getElementById('c-' + c);
      if (comp) comp.classList.toggle('done', !!state[c]);
      if (state[c] && !seen[c]) { seen[c] = 1; picked++; }
    });
    var pct = total ? Math.round(picked / total * 100) : 0;
    document.getElementById('pfill').style.width = pct + '%';
    document.getElementById('pcount').textContent = picked + ' of ' + total;
    var bar = document.querySelector('.pbar');
    if (bar) bar.setAttribute('aria-valuenow', picked);
  }

  rows.forEach(function(r){
    r.querySelector('input').addEventListener('change', function(){
      var c = r.getAttribute('data-c'), l = r.getAttribute('data-l');
      /* one prompt per competency: ticking B unticks A */
      state[c] = (state[c] === l) ? null : l;
      if (!state[c]) delete state[c];
      try { localStorage.setItem(KEY, JSON.stringify(state)); } catch(e) {}
      paint();
    });
  });
  paint();
}());
</script>

<script>
(function(){var id=document.title.replace(/\\W+/g,'-').toLowerCase();
function post(){try{parent.postMessage({frame:id,height:document.documentElement.scrollHeight},'*');}catch(e){}}
if('ResizeObserver' in window){new ResizeObserver(post).observe(document.documentElement);}
window.addEventListener('load',post);window.addEventListener('resize',post);post();})();
</script>
</body>
</html>
`;
}

let done = [];
for (let w = 2; w <= 15; w++) {
  const f = 'week-' + String(w).padStart(2, '0') + '-competencies.html';
  fs.writeFileSync(path.join(ROOT, f), page(w));
  const items = (SHEET[String(w)] || {}).items || [];
  const withP = items.filter(i => (i.a || '').trim() && (i.b || '').trim()).length;
  done.push(f + '  ' + withP + '/' + items.length + ' with prompts');
}
done.forEach(d => console.log(d));
