/* BIO 005 Human Physiology, Progressive Patient File
   Data model. Edit values here, then run build-sim.js.
   Dr. Sharilyn Rennie */

const COURSE = {
  code: "BIO 005",
  title: "Human Physiology",
  section: "BIOL-5-D9286",
  term: "Fall 2026, Sep 8 to Dec 16",
  instructor: "Dr. Sharilyn Rennie",
  masterCode: "RENNIE-KEY-2026"
};

/* ---------- WEEK FRAME ---------- */
/* code: what you post in Canvas to open the week.
   budget: how many orders the student may place that week.
   opens: test categories that become orderable. */

const WEEKS = [
  { n:1, title:"Foundations of Physiology", dates:"Sep 8 to 13", code:"HOMEO-01", budget:6,
    opens:["hx","vs","pe"],
    frame:"You are the physiologist on the case, not the doctor. Your job this week is to establish a baseline and to name the regulated variable that is out of range. Interview and examine before you order anything from a laboratory.",
    predict:"Before you place your first order, write the one physiologic variable you believe is being defended poorly, and what you expect to find.",
    draw:"Draw a labeled negative feedback loop for the variable you named. Mark the sensor, the integrating center, the effector, and the direction each arrow moves.",
    q:[ {k:"loop", type:"select", label:"The loop you drew is best described as", opts:["Negative feedback","Positive feedback","Feedforward","Not a control loop"]},
        {k:"level", type:"select", label:"The level of organization where you think the problem starts", opts:["Molecular","Cellular","Tissue","Organ","Organ system","Whole body"]},
        {k:"why", type:"text", label:"Name one order you deliberately did NOT place this week, and say what would have made you place it."} ] },

  { n:2, title:"Molecules, Water, and Energy", dates:"Sep 14 to 20", code:"BIOMOL-02", budget:5,
    opens:["hx","vs","pe","chem"],
    frame:"Every symptom on this chart is a molecule doing something. This week you connect the patient's intake, storage, and energy use to measurable chemistry.",
    predict:"Name the class of biomolecule you think is most disturbed in this patient and predict the direction of the disturbance before you order.",
    draw:"Draw the pathway from the patient's intake to the molecule you named. Show at least one enzyme step and one storage form.",
    q:[ {k:"class", type:"select", label:"Biomolecule class most disturbed", opts:["Carbohydrate","Lipid","Protein","Nucleic acid","Water and electrolytes","Cannot tell yet"]},
        {k:"bond", type:"select", label:"The property of water most relevant to this patient right now", opts:["Solvent capacity","High heat capacity","Cohesion and surface tension","Ionization and pH","Osmotic behavior"]},
        {k:"why", type:"text", label:"Which result surprised you most, and what did you believe before you saw it?"} ] },

  { n:3, title:"Membranes, Transport, and Compartments", dates:"Sep 21 to 27", code:"MEMBRA-03", budget:5,
    opens:["hx","vs","pe","chem","cbc"],
    frame:"Compartments week. Nearly every number on a chemistry panel is a statement about which side of a membrane something is on.",
    predict:"Predict whether this patient's extracellular volume is low, normal, or high, and name the single measurement that would settle it.",
    draw:"Draw the three fluid compartments to scale for this patient. Mark where you believe water has shifted and draw the osmotic gradient that drove it.",
    q:[ {k:"vol", type:"select", label:"Extracellular fluid volume", opts:["Low","Normal","High","Low with high total body water"]},
        {k:"tonic", type:"select", label:"Plasma tonicity relative to normal", opts:["Hypotonic","Isotonic","Hypertonic"]},
        {k:"trans", type:"select", label:"Transport mechanism most implicated", opts:["Simple diffusion","Facilitated diffusion","Primary active transport","Secondary active transport","Osmosis","Bulk flow"]},
        {k:"why", type:"text", label:"Defend your volume call using two numbers. Say which number you weighted more and why."} ] },

  { n:4, title:"Electrical Signaling", dates:"Sep 28 to Oct 4", code:"ACTPOT-04", budget:5,
    opens:["hx","vs","pe","chem","cbc","card"],
    frame:"Membrane potential is a chemistry problem with a clock on it. This week the patient's electrolytes become an excitability problem.",
    predict:"Predict the direction this patient's resting membrane potential has moved and name the ion responsible.",
    draw:"Draw an action potential trace for this patient beside a normal trace. Label threshold, and show how the patient's electrolytes change the shape or the timing.",
    q:[ {k:"rmp", type:"select", label:"Resting membrane potential in excitable tissue", opts:["More negative than normal","Normal","Less negative than normal","Unstable"]},
        {k:"ion", type:"select", label:"Ion most responsible", opts:["Sodium","Potassium","Calcium","Chloride","Hydrogen","Magnesium"]},
        {k:"excite", type:"select", label:"Net effect on excitability", opts:["Increased then decreased","Increased","Decreased","No change"]},
        {k:"why", type:"text", label:"If you could order only one more test to test this prediction, what would it be and what result would prove you wrong?"} ] },

  { n:5, title:"The Nervous System", dates:"Oct 5 to 11", code:"NEURAL-05", budget:5,
    opens:["hx","vs","pe","chem","cbc","card","neuro"],
    frame:"Autonomic week. Read the vitals as an output of the nervous system, not just as numbers.",
    predict:"Predict whether sympathetic or parasympathetic outflow is dominant in this patient and name the vital sign that will show it.",
    draw:"Draw the reflex arc that is producing this patient's heart rate. Label the receptor, afferent, center, efferent, and effector.",
    q:[ {k:"ans", type:"select", label:"Dominant autonomic tone", opts:["Sympathetic","Parasympathetic","Balanced","Sympathetic with blunted response"]},
        {k:"reflex", type:"select", label:"Reflex most active", opts:["Baroreceptor","Chemoreceptor","Stretch reflex","Withdrawal reflex","None of these"]},
        {k:"why", type:"text", label:"Your patient's heart rate is what it is for a reason. Give the mechanism, not the label."} ] },

  { n:6, title:"Muscle", dates:"Oct 12 to 18", code:"SARCOM-06", budget:5,
    opens:["hx","vs","pe","chem","cbc","card","neuro","musc"],
    frame:"Weakness is a word patients use for a dozen different mechanisms. This week you separate them.",
    predict:"Predict where this patient's weakness originates: fuel, excitation, coupling, or contractile apparatus.",
    draw:"Draw the cross bridge cycle and circle the step you believe is impaired in this patient. If no step is impaired, draw the length tension curve and mark where the patient is operating.",
    q:[ {k:"site", type:"select", label:"Site of the problem", opts:["Fuel supply","Neuromuscular junction","Excitation contraction coupling","Contractile proteins","Not a muscle problem"]},
        {k:"fiber", type:"select", label:"Fiber type most affected", opts:["Slow oxidative","Fast oxidative glycolytic","Fast glycolytic","Cardiac","Smooth","All equally"]},
        {k:"why", type:"text", label:"Explain how you ruled out one of the other three sites."} ] },

  { n:7, title:"Chemical Signaling and Endocrine Control", dates:"Oct 19 to 25", code:"ENDOAX-07", budget:6,
    opens:["hx","vs","pe","chem","cbc","card","neuro","musc","endo"],
    frame:"Axis week. A hormone level alone means nothing. A hormone level next to its tropic hormone is a diagnosis.",
    predict:"Predict which endocrine axis is disturbed and whether the lesion is at the gland or above it. Order the tropic hormone and the target hormone together.",
    draw:"Draw the axis you suspect from hypothalamus to target tissue. Mark where the feedback is broken with an X and show what happens to each level as a result.",
    q:[ {k:"axis", type:"select", label:"Axis disturbed", opts:["Thyroid","Adrenal cortex","Pancreatic islet","Calcium and PTH","Renin angiotensin aldosterone","Growth hormone","None"]},
        {k:"site", type:"select", label:"Level of the lesion", opts:["Primary, at the target gland","Secondary, at the pituitary","Tertiary, at the hypothalamus","Target tissue resistance"]},
        {k:"pair", type:"text", label:"Write the two values you paired and state the rule that let you localize the lesion."} ] },

  { n:8, title:"Reproductive Physiology", dates:"Oct 26 to Nov 1", code:"GONADS-08", budget:4,
    opens:["hx","vs","pe","chem","cbc","card","neuro","musc","endo","repro"],
    frame:"The reproductive axis is the most sensitive alarm in the body. It quiets down when anything systemic is wrong, which makes it a useful reporter.",
    predict:"Predict whether this patient's reproductive axis is suppressed, normal, or overdriven, and say what systemic condition would do that.",
    draw:"Draw the hypothalamic pituitary gonadal axis and add an arrow showing where this patient's systemic illness feeds into it.",
    q:[ {k:"repro", type:"select", label:"Reproductive axis status", opts:["Suppressed","Normal","Overdriven","Not assessable from the data I have"]},
        {k:"why", type:"text", label:"State one finding from an earlier week that supports your call. Cite the week."} ] },

  { n:9, title:"Digestion, Absorption, and Energy Balance", dates:"Nov 2 to 8", code:"ABSORB-09", budget:6,
    opens:["hx","vs","pe","chem","cbc","card","neuro","musc","endo","repro","gi"],
    frame:"Intake, absorption, loss. Three places a nutrient balance can break, and the chart usually tells you which one.",
    predict:"Predict whether this patient's problem is intake, absorption, or loss, and name the nutrient or fuel involved.",
    draw:"Draw a balance diagram for the substance you named: intake in, storage in the middle, losses out. Put this patient's numbers on the arrows where you have them.",
    q:[ {k:"break", type:"select", label:"Where the balance breaks", opts:["Intake","Digestion","Absorption","Storage or mobilization","Loss","Utilization"]},
        {k:"fuel", type:"select", label:"Substance in negative or positive balance", opts:["Glucose","Fat","Protein","Iron","Sodium","Potassium","Water","Calcium"]},
        {k:"why", type:"text", label:"You had a hypothesis in Week 2 about biomolecules. Has it survived? Say what changed it or what confirmed it."} ] },

  { n:10, title:"Cardiac Function and Blood", dates:"Nov 9 to 15", code:"CARDIO-10", budget:6,
    opens:["hx","vs","pe","chem","cbc","card","neuro","musc","endo","repro","gi","fe"],
    frame:"Oxygen delivery week. Cardiac output times arterial oxygen content is the number that matters, and it has four ways to fail.",
    predict:"Predict which term of oxygen delivery is failing in this patient: heart rate, stroke volume, hemoglobin, or saturation.",
    draw:"Draw a full CBC report card for your patient with the indices you ordered, then draw the red cell you would expect to see under the microscope with size and color labeled.",
    q:[ {k:"do2", type:"select", label:"Failing term in oxygen delivery", opts:["Heart rate","Stroke volume","Hemoglobin concentration","Arterial saturation","None, delivery is adequate"]},
        {k:"anemia", type:"select", label:"If anemia is present, classify it", opts:["Microcytic","Normocytic","Macrocytic","No anemia"]},
        {k:"comp", type:"text", label:"Name the compensation this patient is running and the cost of running it."} ] },

  { n:11, title:"Circulation and Blood Pressure", dates:"Nov 16 to 22", code:"HEMODY-11", budget:6,
    opens:["hx","vs","pe","chem","cbc","card","neuro","musc","endo","repro","gi","fe","vasc"],
    frame:"Pressure equals flow times resistance. When the pressure is wrong, one of those two moved, and something moved it on purpose.",
    predict:"Predict whether this patient's blood pressure problem is a cardiac output problem or a resistance problem, and name the hormone or reflex driving it.",
    draw:"Draw a capillary with the four Starling forces labeled and numbered for this patient. Show the net direction of fluid movement at the arterial end and the venous end.",
    q:[ {k:"mech", type:"select", label:"Primary mechanism", opts:["Cardiac output","Systemic vascular resistance","Blood volume","Venous capacitance","Combination"]},
        {k:"driver", type:"select", label:"Driver", opts:["Sympathetic outflow","Angiotensin II","Aldosterone","Antidiuretic hormone","Natriuretic peptide","Loss of volume","None of these"]},
        {k:"starling", type:"text", label:"Give your net filtration pressure at the arterial end in mmHg and show the arithmetic."} ] },

  { n:12, title:"Fluid, Electrolyte, and Acid Base Chemistry", dates:"Nov 23 to 29", code:"ACIDBA-12", budget:6,
    opens:["hx","vs","pe","chem","cbc","card","neuro","musc","endo","repro","gi","fe","vasc","abg"],
    frame:"Four questions, in order, every time. Acidemia or alkalemia. Respiratory or metabolic. Compensated or not. Anion gap or not.",
    predict:"Predict this patient's arterial pH and the primary disturbance before you order the gas. Write the number, not a direction.",
    draw:"Draw the Henderson Hasselbalch relationship as a seesaw with bicarbonate on one side and carbon dioxide on the other. Position this patient's seesaw and show the compensation arrow.",
    q:[ {k:"ph", type:"select", label:"Acid base state", opts:["Acidemia","Alkalemia","Normal pH with mixed disturbance","Normal"]},
        {k:"prim", type:"select", label:"Primary disturbance", opts:["Metabolic acidosis","Respiratory acidosis","Metabolic alkalosis","Respiratory alkalosis","Mixed"]},
        {k:"comp", type:"select", label:"Compensation", opts:["None yet","Partial","Full","Overcorrected, suggests a second disturbance"]},
        {k:"gap", type:"text", label:"Calculate the anion gap. Show the numbers you used and state whether it is elevated."} ] },

  { n:13, title:"Respiration", dates:"Nov 30 to Dec 6", code:"VENTIL-13", budget:6,
    opens:["hx","vs","pe","chem","cbc","card","neuro","musc","endo","repro","gi","fe","vasc","abg","pft"],
    frame:"Ventilation, diffusion, perfusion, carriage. Four steps between room air and a mitochondrion, and this patient fails at one of them.",
    predict:"Predict which of the four steps fails in this patient and predict whether carbon dioxide will be high, low, or normal.",
    draw:"Draw the oxygen hemoglobin dissociation curve. Plot this patient's point on it, then draw the shift their chemistry would cause and label the direction.",
    q:[ {k:"step", type:"select", label:"Step that fails", opts:["Ventilation","Diffusion at the alveolus","Perfusion and matching","Oxygen carriage in blood","Tissue utilization","None"]},
        {k:"shift", type:"select", label:"Dissociation curve shift", opts:["Right","Left","No shift","Right at tissue, left at lung"]},
        {k:"drive", type:"text", label:"What is driving this patient's respiratory rate right now? Name the receptor and the stimulus."} ] },

  { n:14, title:"Renal Function", dates:"Dec 7 to 13", code:"NEPHRO-14", budget:6,
    opens:["hx","vs","pe","chem","cbc","card","neuro","musc","endo","repro","gi","fe","vasc","abg","pft","renal"],
    frame:"Filter, reabsorb, secrete, excrete. The urine is the kidney telling you what the rest of the body asked it to do.",
    predict:"Predict what this patient's urine will show and say what that would prove about the kidney's instructions.",
    draw:"Draw a nephron and mark, segment by segment, where this patient's handling of sodium, water, potassium, and hydrogen ion differs from normal.",
    q:[ {k:"renal", type:"select", label:"Kidney status", opts:["Normal kidney responding correctly","Normal kidney responding to a hormone signal","Intrinsic kidney disease","Prerenal","Postrenal"]},
        {k:"seg", type:"select", label:"Segment most implicated", opts:["Glomerulus","Proximal tubule","Loop of Henle","Distal tubule","Collecting duct","Whole nephron"]},
        {k:"why", type:"text", label:"Is the kidney the problem or the messenger? Defend it in three sentences."} ] },

  { n:15, title:"Case Conference", dates:"Dec 14 to 16", code:"CONFER-15", budget:3,
    opens:["hx","vs","pe","chem","cbc","card","neuro","musc","endo","repro","gi","fe","vasc","abg","pft","renal"],
    frame:"Final week. You name the condition, and more importantly you show the path you took to get there, including the wrong turns.",
    predict:"Write your final diagnosis in one sentence before you place your last three orders. You may not change it after the results appear.",
    draw:"Draw the whole case as one integrated map. Every system you touched, connected, with the primary lesion at the center and arrows outward to each consequence.",
    q:[ {k:"dx", type:"text", label:"Final diagnosis, one sentence."},
        {k:"first", type:"text", label:"What was your first serious hypothesis, in which week, and what killed it?"},
        {k:"cheap", type:"text", label:"Which single order in the whole term gave you the most information for its cost, and why?"},
        {k:"wrong", type:"text", label:"Name one thing you still cannot explain about this patient."} ] }
];

/* ---------- CATEGORIES ---------- */
const CATS = {
  hx:   { label:"Interview", note:"Start here. The story is the cheapest information you will ever get from this patient." },
  vs:   { label:"Vitals and measurements", note:"" },
  pe:   { label:"Physical examination", note:"" },
  chem: { label:"Blood chemistry", note:"" },
  cbc:  { label:"Hematology", note:"" },
  fe:   { label:"Iron studies", note:"" },
  endo: { label:"Endocrine", note:"Order tropic and target hormones together or you will learn nothing." },
  repro:{ label:"Reproductive", note:"" },
  card: { label:"Cardiac", note:"" },
  vasc: { label:"Vascular and volume", note:"" },
  abg:  { label:"Blood gas", note:"" },
  pft:  { label:"Pulmonary function", note:"" },
  renal:{ label:"Urine and renal", note:"" },
  gi:   { label:"Gastrointestinal", note:"" },
  neuro:{ label:"Neurologic", note:"" },
  musc: { label:"Muscle", note:"" }
};

/* ---------- TEST CATALOG ----------
   cost: order tokens. ref: reference range shown with the result. */
const TESTS = [
  // Interview
  {id:"hx_chief",  cat:"hx", name:"Chief concern in the patient's own words", cost:1, ref:""},
  {id:"hx_time",   cat:"hx", name:"Symptom timeline", cost:1, ref:""},
  {id:"hx_meds",   cat:"hx", name:"Medications and supplements", cost:1, ref:""},
  {id:"hx_diet",   cat:"hx", name:"Diet and fluid intake", cost:1, ref:""},
  {id:"hx_social", cat:"hx", name:"Work, sleep, and activity", cost:1, ref:""},
  {id:"hx_fam",    cat:"hx", name:"Family history", cost:1, ref:""},
  {id:"hx_ros",    cat:"hx", name:"Review of systems", cost:2, ref:"", minWeek:2},

  // Vitals
  {id:"vs_hr",    cat:"vs", name:"Heart rate", cost:1, ref:"60 to 100 per minute"},
  {id:"vs_bp",    cat:"vs", name:"Blood pressure, seated", cost:1, ref:"under 120 over 80 mmHg"},
  {id:"vs_rr",    cat:"vs", name:"Respiratory rate", cost:1, ref:"12 to 20 per minute"},
  {id:"vs_temp",  cat:"vs", name:"Core temperature", cost:1, ref:"36.5 to 37.5 C"},
  {id:"vs_spo2",  cat:"vs", name:"Pulse oximetry on room air", cost:1, ref:"95 to 100 percent"},
  {id:"vs_wt",    cat:"vs", name:"Weight and weight change", cost:1, ref:""},
  {id:"vs_ortho", cat:"vs", name:"Orthostatic vital signs", cost:2, ref:"Drop under 20 systolic, under 10 diastolic", minWeek:5},

  // Exam
  {id:"pe_skin",  cat:"pe", name:"Skin, nails, and mucous membranes", cost:1, ref:""},
  {id:"pe_card",  cat:"pe", name:"Cardiac auscultation and jugular venous pressure", cost:1, ref:""},
  {id:"pe_lung",  cat:"pe", name:"Lung auscultation and work of breathing", cost:1, ref:""},
  {id:"pe_edema", cat:"pe", name:"Peripheral edema and capillary refill", cost:1, ref:""},
  {id:"pe_abd",   cat:"pe", name:"Abdominal examination", cost:1, ref:""},
  {id:"pe_thy",   cat:"pe", name:"Neck and thyroid examination", cost:1, ref:""},

  // Chemistry
  {id:"na",   cat:"chem", name:"Sodium", cost:1, ref:"135 to 145 mEq/L"},
  {id:"k",    cat:"chem", name:"Potassium", cost:1, ref:"3.5 to 5.0 mEq/L"},
  {id:"cl",   cat:"chem", name:"Chloride", cost:1, ref:"98 to 107 mEq/L"},
  {id:"hco3", cat:"chem", name:"Bicarbonate, venous", cost:1, ref:"22 to 28 mEq/L"},
  {id:"bun",  cat:"chem", name:"Blood urea nitrogen", cost:1, ref:"7 to 20 mg/dL"},
  {id:"cr",   cat:"chem", name:"Creatinine", cost:1, ref:"0.6 to 1.2 mg/dL"},
  {id:"glu",  cat:"chem", name:"Glucose, fasting", cost:1, ref:"70 to 99 mg/dL"},
  {id:"ca",   cat:"chem", name:"Calcium, total", cost:1, ref:"8.5 to 10.5 mg/dL"},
  {id:"phos", cat:"chem", name:"Phosphate", cost:1, ref:"2.5 to 4.5 mg/dL"},
  {id:"mg",   cat:"chem", name:"Magnesium", cost:1, ref:"1.7 to 2.2 mg/dL"},
  {id:"alb",  cat:"chem", name:"Albumin", cost:1, ref:"3.5 to 5.0 g/dL"},
  {id:"osm",  cat:"chem", name:"Serum osmolality, measured", cost:2, ref:"275 to 295 mOsm/kg"},
  {id:"lip",  cat:"chem", name:"Lipid panel", cost:2, ref:"LDL under 100 mg/dL", minWeek:2},
  {id:"ck",   cat:"chem", name:"Creatine kinase", cost:2, ref:"30 to 200 U/L", minWeek:6},

  // Hematology
  {id:"hgb",  cat:"cbc", name:"Hemoglobin", cost:1, ref:"12.0 to 16.0 g/dL"},
  {id:"hct",  cat:"cbc", name:"Hematocrit", cost:1, ref:"36 to 48 percent"},
  {id:"mcv",  cat:"cbc", name:"Mean corpuscular volume", cost:1, ref:"80 to 100 fL"},
  {id:"rdw",  cat:"cbc", name:"Red cell distribution width", cost:1, ref:"11.5 to 14.5 percent"},
  {id:"wbc",  cat:"cbc", name:"White cell count with differential", cost:1, ref:"4.5 to 11.0 thousand/microliter"},
  {id:"plt",  cat:"cbc", name:"Platelet count", cost:1, ref:"150 to 400 thousand/microliter"},
  {id:"retic",cat:"cbc", name:"Reticulocyte percentage", cost:2, ref:"0.5 to 2.5 percent"},
  {id:"smear",cat:"cbc", name:"Peripheral blood smear description", cost:2, ref:"", minWeek:10},

  // Iron
  {id:"ferr", cat:"fe", name:"Ferritin", cost:2, ref:"15 to 200 ng/mL", minWeek:9},
  {id:"iron", cat:"fe", name:"Serum iron", cost:1, ref:"60 to 170 mcg/dL", minWeek:9},
  {id:"tibc", cat:"fe", name:"Total iron binding capacity", cost:1, ref:"240 to 450 mcg/dL", minWeek:9},
  {id:"tsat", cat:"fe", name:"Transferrin saturation", cost:1, ref:"20 to 50 percent", minWeek:9},

  // Endocrine
  {id:"tsh",  cat:"endo", name:"Thyroid stimulating hormone", cost:2, ref:"0.4 to 4.0 mIU/L", minWeek:7},
  {id:"ft4",  cat:"endo", name:"Free thyroxine", cost:2, ref:"0.8 to 1.8 ng/dL", minWeek:7},
  {id:"tpo",  cat:"endo", name:"Thyroid peroxidase antibody", cost:2, ref:"under 35 IU/mL", minWeek:7},
  {id:"cort", cat:"endo", name:"Morning cortisol", cost:2, ref:"6 to 23 mcg/dL", minWeek:7},
  {id:"acth", cat:"endo", name:"Adrenocorticotropic hormone", cost:2, ref:"7 to 63 pg/mL", minWeek:7},
  {id:"aldo", cat:"endo", name:"Plasma aldosterone", cost:2, ref:"4 to 31 ng/dL", minWeek:7},
  {id:"renin",cat:"endo", name:"Plasma renin activity", cost:2, ref:"0.5 to 4.0 ng/mL/hr", minWeek:7},
  {id:"pth",  cat:"endo", name:"Parathyroid hormone, intact", cost:2, ref:"15 to 65 pg/mL", minWeek:7},
  {id:"a1c",  cat:"endo", name:"Hemoglobin A1c", cost:2, ref:"4.0 to 5.6 percent", minWeek:7},
  {id:"cpep", cat:"endo", name:"C peptide", cost:2, ref:"0.8 to 3.9 ng/mL", minWeek:7},
  {id:"vitd", cat:"endo", name:"25 hydroxy vitamin D", cost:2, ref:"30 to 100 ng/mL", minWeek:7},

  // Reproductive
  {id:"lhfsh", cat:"repro", name:"Luteinizing hormone and follicle stimulating hormone", cost:2, ref:"varies by phase and sex", minWeek:8},
  {id:"sexh",  cat:"repro", name:"Estradiol or testosterone", cost:2, ref:"varies by sex", minWeek:8},
  {id:"cyc",   cat:"repro", name:"Menstrual or reproductive history detail", cost:1, ref:"", minWeek:8},

  // Cardiac
  {id:"ecg",  cat:"card", name:"Twelve lead electrocardiogram", cost:2, ref:"", minWeek:4},
  {id:"echo", cat:"card", name:"Echocardiogram with ejection fraction", cost:3, ref:"Ejection fraction 55 to 70 percent", minWeek:10},
  {id:"bnp",  cat:"card", name:"B type natriuretic peptide", cost:2, ref:"under 100 pg/mL", minWeek:10},
  {id:"trop", cat:"card", name:"High sensitivity troponin", cost:2, ref:"under 14 ng/L", minWeek:10},

  // Vascular
  {id:"map",   cat:"vasc", name:"Mean arterial pressure and pulse pressure", cost:1, ref:"MAP 70 to 100 mmHg", minWeek:11},
  {id:"jvp",   cat:"vasc", name:"Estimated central venous pressure", cost:2, ref:"2 to 8 mmHg", minWeek:11},
  {id:"cap",   cat:"vasc", name:"Capillary Starling force estimates", cost:3, ref:"", minWeek:11},
  {id:"amb",   cat:"vasc", name:"Ambulatory blood pressure over 24 hours", cost:2, ref:"", minWeek:11},

  // Blood gas
  {id:"ph",    cat:"abg", name:"Arterial pH", cost:2, ref:"7.35 to 7.45", minWeek:12},
  {id:"pco2",  cat:"abg", name:"Arterial carbon dioxide tension", cost:2, ref:"35 to 45 mmHg", minWeek:12},
  {id:"po2",   cat:"abg", name:"Arterial oxygen tension", cost:2, ref:"80 to 100 mmHg", minWeek:12},
  {id:"abg_hco3", cat:"abg", name:"Arterial bicarbonate, calculated", cost:1, ref:"22 to 26 mEq/L", minWeek:12},
  {id:"lact",  cat:"abg", name:"Lactate", cost:2, ref:"0.5 to 2.0 mmol/L", minWeek:12},

  // Pulmonary
  {id:"fev1",  cat:"pft", name:"Forced expiratory volume in one second", cost:2, ref:"over 80 percent predicted", minWeek:13},
  {id:"fvc",   cat:"pft", name:"Forced vital capacity", cost:2, ref:"over 80 percent predicted", minWeek:13},
  {id:"ratio", cat:"pft", name:"FEV1 to FVC ratio", cost:1, ref:"over 0.70", minWeek:13},
  {id:"dlco",  cat:"pft", name:"Diffusing capacity for carbon monoxide", cost:2, ref:"over 80 percent predicted", minWeek:13},
  {id:"walk",  cat:"pft", name:"Six minute walk with oximetry", cost:2, ref:"", minWeek:13},

  // Renal and urine
  {id:"ua",    cat:"renal", name:"Urinalysis, dipstick and microscopy", cost:2, ref:"", minWeek:14},
  {id:"usg",   cat:"renal", name:"Urine specific gravity", cost:1, ref:"1.005 to 1.030", minWeek:14},
  {id:"uosm",  cat:"renal", name:"Urine osmolality", cost:2, ref:"50 to 1200 mOsm/kg", minWeek:14},
  {id:"una",   cat:"renal", name:"Urine sodium", cost:2, ref:"varies with intake", minWeek:14},
  {id:"uk",    cat:"renal", name:"Urine potassium, 24 hour", cost:2, ref:"25 to 125 mEq/day", minWeek:14},
  {id:"acr",   cat:"renal", name:"Urine albumin to creatinine ratio", cost:2, ref:"under 30 mg/g", minWeek:14},
  {id:"egfr",  cat:"renal", name:"Estimated glomerular filtration rate", cost:1, ref:"over 90 mL/min/1.73 m2", minWeek:14},

  // GI
  {id:"fobt", cat:"gi", name:"Fecal occult blood test", cost:2, ref:"Negative", minWeek:9},
  {id:"celiac", cat:"gi", name:"Tissue transglutaminase antibody", cost:2, ref:"under 4 U/mL", minWeek:9},
  {id:"scope", cat:"gi", name:"Upper endoscopy and colonoscopy report", cost:3, ref:"", minWeek:9},

  // Neuro
  {id:"dtr",  cat:"neuro", name:"Deep tendon reflexes with relaxation phase", cost:1, ref:"2 plus and symmetric", minWeek:5},
  {id:"cn",   cat:"neuro", name:"Cranial nerve screen", cost:1, ref:"", minWeek:5},
  {id:"sens", cat:"neuro", name:"Sensory examination including vibration", cost:1, ref:"", minWeek:5},
  {id:"hrv",  cat:"neuro", name:"Heart rate variability with deep breathing", cost:2, ref:"", minWeek:5},

  // Muscle
  {id:"str",  cat:"musc", name:"Manual muscle strength testing", cost:1, ref:"5 of 5 throughout", minWeek:6},
  {id:"grip", cat:"musc", name:"Grip dynamometry", cost:1, ref:"", minWeek:6},
  {id:"emg",  cat:"musc", name:"Electromyography", cost:3, ref:"", minWeek:6}
];

/* ---------- NORMAL RESULTS (default when a variant does not override) ---------- */
const NORMALS = {
  hx_chief:"I feel like something is off but I cannot put my finger on it.",
  hx_time:"Symptoms have been present for several months without a clear starting point.",
  hx_meds:"No prescription medications. Occasional over the counter analgesic.",
  hx_diet:"Mixed diet, three meals most days, about 1.5 liters of fluid daily.",
  hx_social:"Works full time, sleeps six to seven hours, walks for exercise a few times a week.",
  hx_fam:"No known family history of chronic disease.",
  hx_ros:"No fever, no chest pain, no visual change, no bowel or bladder change reported.",
  vs_hr:"78 per minute, regular", vs_bp:"118 over 74 mmHg", vs_rr:"14 per minute",
  vs_temp:"36.9 C", vs_spo2:"98 percent", vs_wt:"Stable over the last year",
  vs_ortho:"No significant orthostatic change.",
  pe_skin:"Warm and dry. Mucous membranes moist and pink. Nails normal.",
  pe_card:"Regular rate and rhythm. No murmur. Jugular venous pressure not elevated.",
  pe_lung:"Clear to auscultation. Normal work of breathing.",
  pe_edema:"No edema. Capillary refill under two seconds.",
  pe_abd:"Soft, nontender, no organomegaly.",
  pe_thy:"Thyroid not enlarged, no nodule, nontender.",
  na:"140 mEq/L", k:"4.2 mEq/L", cl:"103 mEq/L", hco3:"25 mEq/L",
  bun:"14 mg/dL", cr:"0.9 mg/dL", glu:"88 mg/dL", ca:"9.4 mg/dL",
  phos:"3.4 mg/dL", mg:"2.0 mg/dL", alb:"4.3 g/dL", osm:"288 mOsm/kg",
  lip:"Total cholesterol 178, LDL 96, HDL 54, triglycerides 118 mg/dL",
  ck:"96 U/L",
  hgb:"13.8 g/dL", hct:"41 percent", mcv:"89 fL", rdw:"13.1 percent",
  wbc:"6.8 thousand/microliter, normal differential", plt:"248 thousand/microliter",
  retic:"1.2 percent", smear:"Normocytic normochromic red cells. No abnormal forms.",
  ferr:"84 ng/mL", iron:"96 mcg/dL", tibc:"312 mcg/dL", tsat:"31 percent",
  tsh:"1.9 mIU/L", ft4:"1.2 ng/dL", tpo:"under 10 IU/mL",
  cort:"14.2 mcg/dL", acth:"28 pg/mL", aldo:"12 ng/dL", renin:"1.4 ng/mL/hr",
  pth:"38 pg/mL", a1c:"5.2 percent", cpep:"1.9 ng/mL", vitd:"42 ng/mL",
  lhfsh:"Within reference range for age and phase.",
  sexh:"Within reference range for age and sex.",
  cyc:"Regular pattern, no change reported.",
  ecg:"Normal sinus rhythm. Normal axis. No ST or T wave abnormality. QTc 412 ms.",
  echo:"Ejection fraction 62 percent. Normal chamber sizes. No valve abnormality.",
  bnp:"38 pg/mL", trop:"under 4 ng/L",
  map:"89 mmHg mean, pulse pressure 44 mmHg",
  jvp:"5 mmHg", amb:"Normal daytime average with expected night dipping.",
  cap:"Capillary hydrostatic 35 mmHg arterial end and 16 mmHg venous end. Plasma colloid osmotic 25 mmHg. Interstitial hydrostatic 0 mmHg. Interstitial colloid osmotic 0 mmHg.",
  ph:"7.40", pco2:"40 mmHg", po2:"94 mmHg", abg_hco3:"24 mEq/L", lact:"1.1 mmol/L",
  fev1:"96 percent predicted", fvc:"98 percent predicted", ratio:"0.81",
  dlco:"92 percent predicted", walk:"480 meters, saturation stayed at 97 percent.",
  ua:"Clear yellow. Protein negative. Glucose negative. Ketones negative. Blood negative. No cells or casts.",
  usg:"1.018", uosm:"620 mOsm/kg", una:"64 mEq/L", uk:"58 mEq/day",
  acr:"6 mg/g", egfr:"over 90 mL/min/1.73 m2",
  fobt:"Negative", celiac:"under 2 U/mL",
  scope:"No mucosal lesion identified in the examined segments.",
  dtr:"2 plus and symmetric with normal relaxation.",
  cn:"Cranial nerves two through twelve intact.",
  sens:"Light touch, vibration, and proprioception intact.",
  hrv:"Normal sinus arrhythmia with deep breathing.",
  str:"5 of 5 in all tested groups.",
  grip:"At the expected percentile for age and sex.",
  emg:"Normal insertional activity and motor unit potentials."
};

/* ---------- VARIANTS ---------- */
/* label is the answer key. Students never see it.
   beats[i] is the week i+1 development. Keep each under 30 words. */

const VARIANTS = [
{
  id:"A", who:"Marisol V., 34", role:"warehouse order picker",
  label:"Iron deficiency anemia from chronic occult gastrointestinal blood loss, aggravated by regular NSAID use",
  teach:"Microcytic anemia, oxygen delivery, iron balance, the difference between a low store and a low intake",
  beats:[
   "Arrived tired. Says she can climb one flight of stairs at work before she has to stop and breathe.",
   "Reports craving and chewing ice all day. Has been taking ibuprofen for back pain most days for a year.",
   "No swelling anywhere. Says she is drinking more water than usual because she feels warm and thirsty at work.",
   "Notes her heart pounding at rest in the evening. No palpitation during sleep.",
   "Light headed when she stands up fast on the loading dock. It passes in a few seconds.",
   "Legs feel heavy after twenty minutes on the floor. Grip is fine. Recovery is slow.",
   "Periods have been heavy for two years. She assumed that was normal for her.",
   "Reports no change in cycle length, but soaking through protection on the first two days.",
   "Stool has looked dark on and off. She thought it was the iron pills a friend gave her, but she never took them.",
   "Nail beds are pale. She brings a photo of her tongue looking smooth and shiny.",
   "Blood pressure is on the low side of normal and her pulse pressure is wide.",
   "No breathlessness at rest. Says she can talk in full sentences even when she feels worst.",
   "Oxygen saturation is normal every time it is measured, which she finds confusing.",
   "Urine looks normal to her. She has never had swelling of the face or feet.",
   "Final visit. She wants to know why her oxygen reading was always fine if she was short of breath."
  ],
  r:{
   hx_chief:"I am tired all the time and I get out of breath carrying boxes I used to carry fine.",
   hx_time:"Gradual over about eighteen months. Worse in the last three.",
   hx_meds:"Ibuprofen 600 mg most days for low back pain. No prescription medicines.",
   hx_diet:"Skips breakfast. Coffee and a sandwich at lunch. Very little red meat. Chews ice constantly.",
   hx_social:"Ten hour shifts on her feet. Sleeps five to six hours. No tobacco.",
   hx_fam:"Mother had anemia in pregnancy. No other known illness.",
   hx_ros:"No fever. No chest pain. Heavy menstrual bleeding. Dark stools intermittently.",
   vs_hr:"104 per minute, regular", vs_bp:"106 over 62 mmHg", vs_rr:"18 per minute",
   vs_spo2:"98 percent", vs_wt:"Down 2 kg over a year, unintentional",
   vs_ortho:"Systolic falls 14 mmHg on standing, heart rate rises to 122.",
   pe_skin:"Conjunctivae pale. Nail beds pale with early spooning. Tongue smooth and glossy.",
   pe_card:"Tachycardic. Soft systolic flow murmur at the left sternal border. Jugular venous pressure normal.",
   hgb:"9.1 g/dL", hct:"28 percent", mcv:"71 fL", rdw:"18.2 percent",
   plt:"468 thousand/microliter", retic:"0.8 percent",
   smear:"Microcytic hypochromic red cells with marked variation in size and shape. Occasional pencil cell.",
   ferr:"6 ng/mL", iron:"28 mcg/dL", tibc:"486 mcg/dL", tsat:"6 percent",
   fobt:"Positive on two of three cards",
   scope:"Two shallow gastric antral erosions with recent bleeding stigmata. Colon normal.",
   ecg:"Sinus tachycardia at 104. Otherwise normal.",
   map:"77 mmHg mean, pulse pressure 44 mmHg",
   cyc:"Cycle every 26 days, seven days of flow, soaking through protection on days one and two.",
   po2:"96 mmHg", ph:"7.41", pco2:"38 mmHg"
  }
},
{
  id:"B", who:"Dana W., 47", role:"bookkeeper",
  label:"Primary hypothyroidism from Hashimoto thyroiditis, with secondary hyponatraemia and myopathy",
  teach:"Endocrine axis localisation, basal metabolic rate, why a hormone level is meaningless without its tropic hormone",
  beats:[
   "Says she is cold when everyone else is comfortable, and she has been sleeping ten hours and waking tired.",
   "Weight is up seven kilograms in eight months with no change in what she eats.",
   "Face looks puffy in the morning. She says her rings are tight but her ankles do not pit.",
   "Resting heart rate is in the fifties. She has never been an athlete.",
   "Reflex testing shows a normal contraction and a slow, hanging return.",
   "Muscles ache after ordinary activity. She stopped her walking group two months ago.",
   "Neck feels full when she swallows. Her sister has an autoimmune thyroid condition.",
   "Cycles have become heavy and closer together over the last year.",
   "Constipated most days despite plenty of fiber. Appetite is if anything down.",
   "Skin is dry and cool. Hair is thinning at the outer eyebrow.",
   "Blood pressure is mildly elevated with a narrow pulse pressure.",
   "Sodium has drifted down on every panel. She has not changed her fluid intake.",
   "No breathlessness. She says the tiredness is not a lung tiredness, it is a whole body tiredness.",
   "Urine output is normal and she is not thirsty.",
   "Final visit. She wants to know why her sodium was low if she was not dehydrated."
  ],
  r:{
   hx_chief:"I am cold, I am exhausted, and I am gaining weight without eating more.",
   hx_time:"Slow over about a year, worse since the spring.",
   hx_meds:"None. Takes a multivitamin most days.",
   hx_diet:"Regular meals, no change in portions. Fluid about 1.5 liters.",
   hx_social:"Desk work. Sleeps nine to ten hours and still tired. No tobacco or alcohol.",
   hx_fam:"Sister with autoimmune thyroid disease. Mother with vitiligo.",
   hx_ros:"Cold intolerance, constipation, dry skin, heavy periods, muscle aching, hoarse voice.",
   vs_hr:"52 per minute, regular", vs_bp:"138 over 88 mmHg", vs_temp:"36.1 C",
   vs_wt:"Up 7 kg in eight months without dietary change",
   pe_skin:"Dry, cool, coarse. Thinning of the lateral eyebrow. Nonpitting puffiness of the face and hands.",
   pe_thy:"Diffusely enlarged, firm, nontender thyroid without discrete nodule.",
   pe_edema:"Nonpitting fullness of the hands. No pitting edema of the ankles.",
   dtr:"2 plus contraction with markedly delayed relaxation phase.",
   na:"131 mEq/L", cl:"96 mEq/L", osm:"272 mOsm/kg", ck:"482 U/L",
   lip:"Total cholesterol 268, LDL 182, HDL 48, triglycerides 190 mg/dL",
   tsh:"42.6 mIU/L", ft4:"0.4 ng/dL", tpo:"640 IU/mL",
   hgb:"11.4 g/dL", hct:"34 percent", mcv:"92 fL", rdw:"13.4 percent", retic:"0.9 percent",
   smear:"Normocytic normochromic red cells. No abnormal forms.",
   ecg:"Sinus bradycardia at 52. Low voltage in the limb leads.",
   uosm:"340 mOsm/kg", una:"46 mEq/L", usg:"1.012",
   str:"4 plus of 5 proximally, 5 of 5 distally.",
   grip:"Below the tenth percentile for age and sex.",
   cyc:"Cycles every 22 days with heavy flow for six days.",
   lhfsh:"Follicle stimulating hormone 7.2 IU/L, luteinizing hormone 5.1 IU/L.",
   cort:"11.8 mcg/dL", acth:"22 pg/mL"
  }
},
{
  id:"C", who:"Theo G., 19", role:"community college student and part time barista",
  label:"New onset type 1 diabetes mellitus with early diabetic ketoacidosis",
  teach:"Osmolarity, anion gap acidosis, respiratory compensation, fuel metabolism without insulin",
  beats:[
   "Says he is drinking constantly and up three or four times a night to urinate.",
   "Has lost eight kilograms in six weeks while eating more than usual.",
   "Mouth is dry, eyes look sunken, and he is thirsty even right after drinking.",
   "Feels weak and a little tingly in the fingers. No focal weakness.",
   "Breathing is deep and steady rather than fast and shallow. He does not feel breathless.",
   "Cramping in the calves at night. Strength testing is normal.",
   "An aunt has an autoimmune thyroid condition. No family history of diabetes.",
   "No change in libido or reproductive symptoms reported.",
   "Appetite is high, intake is high, and he is still losing weight.",
   "Vision blurs and clears over the course of the day.",
   "Blood pressure runs low with a fast pulse. No edema anywhere.",
   "Breath has a sweet, solvent like smell noted at the bedside.",
   "Oxygen saturation is normal. Carbon dioxide is low on every measurement.",
   "Urine output is high and pale, and he says it sometimes looks sticky on the seat.",
   "Final visit. He wants to know why he was losing weight while eating more than ever."
  ],
  r:{
   hx_chief:"I cannot stop drinking water, I am up all night peeing, and I am losing weight.",
   hx_time:"Six weeks, accelerating over the last ten days.",
   hx_meds:"None. No steroids.",
   hx_diet:"Eating more than usual. Four to five liters of water and sports drink daily.",
   hx_social:"Full time student, works evenings. No tobacco. Occasional alcohol.",
   hx_fam:"Aunt with autoimmune thyroid disease. No diabetes in the family.",
   hx_ros:"Polyuria, polydipsia, polyphagia, weight loss, blurred vision, nausea, no fever.",
   vs_hr:"118 per minute, regular", vs_bp:"98 over 58 mmHg", vs_rr:"26 per minute, deep and unlaboured",
   vs_temp:"36.8 C", vs_spo2:"99 percent", vs_wt:"Down 8 kg in six weeks",
   vs_ortho:"Systolic falls 22 mmHg on standing with a rise in heart rate to 136.",
   pe_skin:"Dry with reduced turgor. Mucous membranes dry. Sweet acetone odor on the breath.",
   pe_lung:"Clear. Deep regular respirations without accessory muscle use.",
   na:"129 mEq/L", k:"5.4 mEq/L", cl:"96 mEq/L", hco3:"14 mEq/L",
   bun:"28 mg/dL", cr:"1.2 mg/dL", glu:"412 mg/dL", osm:"306 mOsm/kg", phos:"2.2 mg/dL",
   a1c:"12.1 percent", cpep:"0.2 ng/mL",
   ph:"7.26", pco2:"27 mmHg", po2:"102 mmHg", abg_hco3:"13 mEq/L", lact:"1.6 mmol/L",
   ua:"Glucose 4 plus. Ketones large. Protein trace. No cells or casts.",
   usg:"1.032", uosm:"420 mOsm/kg", una:"52 mEq/L", egfr:"88 mL/min/1.73 m2",
   ecg:"Sinus tachycardia at 118. Peaked T waves in the precordial leads.",
   hgb:"15.6 g/dL", hct:"47 percent", wbc:"13.2 thousand/microliter with neutrophil predominance",
   tsh:"2.4 mIU/L", ft4:"1.1 ng/dL", tpo:"142 IU/mL",
   sens:"Light touch intact. Vibration mildly reduced at the great toe.",
   map:"71 mmHg mean, pulse pressure 40 mmHg"
  }
},
{
  id:"D", who:"Ruben A., 61", role:"retired mail carrier",
  label:"Chronic kidney disease stage 3b with secondary hyperparathyroidism and anemia of chronic kidney disease",
  teach:"Glomerular filtration, mineral bone axis, non anion gap acidosis, erythropoietin",
  beats:[
   "Feels flat and itchy. Says the itching is worst at night and there is no rash.",
   "Appetite is down and food tastes metallic. Weight is slowly falling.",
   "Puffy around the eyes in the morning and mild pitting at the ankles by evening.",
   "No palpitations. Potassium has been drifting up on routine panels for two years.",
   "No focal neurologic symptoms. Sleeps poorly with restless legs.",
   "Muscle cramps in the calves several nights a week.",
   "No thyroid symptoms. He mentions an old note about calcium being low.",
   "No reproductive complaints. Libido reduced over several years.",
   "Nausea in the mornings that improves after he eats.",
   "Skin is pale with a sallow undertone. Nail beds pale.",
   "Blood pressure has needed three medications and is still above target.",
   "Breathing is normal but his bicarbonate has been low on every panel.",
   "No cough or wheeze. Oxygen saturation is normal.",
   "Urine has been foamy in the toilet for at least a year.",
   "Final visit. He wants to know why his bones are being affected by a kidney problem."
  ],
  r:{
   hx_chief:"I have no energy, food tastes like metal, and I itch all night.",
   hx_time:"Creeping up over three or four years.",
   hx_meds:"Amlodipine, lisinopril, hydrochlorothiazide. Occasional ibuprofen for knees.",
   hx_diet:"Small appetite. Salt heavy convenience food. About 1 liter of fluid.",
   hx_social:"Retired. Low activity. Former smoker, quit twenty years ago.",
   hx_fam:"Father had kidney failure. Mother had hypertension.",
   hx_ros:"Fatigue, pruritus, metallic taste, nocturia, restless legs, ankle swelling.",
   vs_hr:"76 per minute, regular", vs_bp:"158 over 94 mmHg", vs_wt:"Down 3 kg over a year",
   pe_skin:"Pale with sallow tone. Excoriations on the forearms without primary rash.",
   pe_edema:"Trace to one plus pitting edema at both ankles by evening.",
   pe_card:"Regular. Fourth heart sound. Jugular venous pressure at the upper limit.",
   na:"138 mEq/L", k:"5.3 mEq/L", cl:"108 mEq/L", hco3:"19 mEq/L",
   bun:"42 mg/dL", cr:"2.4 mg/dL", ca:"8.2 mg/dL", phos:"5.6 mg/dL", alb:"3.6 g/dL",
   pth:"288 pg/mL", vitd:"18 ng/mL", glu:"104 mg/dL", a1c:"5.8 percent",
   hgb:"10.2 g/dL", hct:"31 percent", mcv:"89 fL", rdw:"13.8 percent", retic:"0.7 percent",
   smear:"Normocytic normochromic red cells. Occasional burr cell.",
   ferr:"148 ng/mL", iron:"64 mcg/dL", tibc:"238 mcg/dL", tsat:"27 percent",
   egfr:"26 mL/min/1.73 m2", acr:"640 mg/g",
   ua:"Protein 2 plus. Blood negative. Occasional broad waxy cast. No cells.",
   usg:"1.010", uosm:"320 mOsm/kg", una:"58 mEq/L",
   ph:"7.33", pco2:"34 mmHg", abg_hco3:"18 mEq/L",
   ecg:"Sinus rhythm. Left ventricular hypertrophy by voltage criteria.",
   echo:"Ejection fraction 58 percent with concentric left ventricular hypertrophy and diastolic dysfunction.",
   bnp:"186 pg/mL", map:"115 mmHg mean, pulse pressure 64 mmHg",
   aldo:"14 ng/dL", renin:"0.9 ng/mL/hr", jvp:"9 mmHg"
  }
},
{
  id:"E", who:"June H., 66", role:"retired school kitchen manager",
  label:"Chronic obstructive pulmonary disease with chronic carbon dioxide retention and secondary polycythaemia",
  teach:"Obstructive ventilation, chronic respiratory acidosis with renal compensation, hypoxic drive, oxygen carriage",
  beats:[
   "Breathless walking to the mailbox. Says she has to stop halfway and lean on the fence.",
   "Morning cough with clear sputum most days for years. Smoked for forty years, quit at sixty.",
   "No swelling and no weight gain. She says she has lost weight without trying.",
   "No palpitations. Heart rate sits in the high eighties at rest.",
   "No dizziness. She purses her lips when she exhales without being told to.",
   "Legs tire before her breath does on flat ground, but not on a hill.",
   "No thyroid symptoms. No temperature intolerance.",
   "Post menopausal, no reproductive complaints.",
   "Eats small meals because a full stomach makes it harder to breathe.",
   "Fingertips and lips look dusky in cool weather. Nail beds are thick.",
   "Blood pressure is normal. Jugular venous pressure rises slightly when she coughs.",
   "Bicarbonate has been high on every panel for years and nobody has explained it.",
   "Expiration takes about three times as long as inspiration at the bedside.",
   "Urine output is normal. She has never had protein in the urine.",
   "Final visit. She wants to know why giving her more oxygen once made her sleepy."
  ],
  r:{
   hx_chief:"I run out of air walking to the mailbox and I cough every single morning.",
   hx_time:"Ten years of cough, five years of breathlessness, worse each winter.",
   hx_meds:"Two inhalers, not used consistently. No oxygen at home.",
   hx_diet:"Small frequent meals. Says eating a big meal makes breathing harder.",
   hx_social:"Retired. Forty pack year smoking history, quit six years ago. Lives alone.",
   hx_fam:"Father had emphysema.",
   hx_ros:"Chronic cough, sputum, exertional breathlessness, weight loss, no fever, no chest pain.",
   vs_hr:"92 per minute, regular", vs_bp:"126 over 78 mmHg", vs_rr:"22 per minute",
   vs_spo2:"89 percent on room air", vs_wt:"Down 5 kg over two years",
   pe_skin:"Dusky nail beds. Nails thickened. No clubbing.",
   pe_lung:"Diminished breath sounds throughout. Prolonged expiratory phase. End expiratory wheeze. Accessory muscle use. Pursed lip breathing.",
   pe_card:"Distant heart sounds. Jugular venous pressure normal at rest, rises with cough.",
   hco3:"32 mEq/L", cl:"95 mEq/L", na:"140 mEq/L", k:"4.0 mEq/L",
   hgb:"18.2 g/dL", hct:"54 percent", mcv:"88 fL", retic:"2.2 percent",
   smear:"Increased red cell mass. Normal morphology.",
   ph:"7.36", pco2:"58 mmHg", po2:"58 mmHg", abg_hco3:"32 mEq/L", lact:"1.2 mmol/L",
   fev1:"38 percent predicted", fvc:"72 percent predicted", ratio:"0.44",
   dlco:"44 percent predicted",
   walk:"210 meters with saturation falling from 89 to 82 percent.",
   ecg:"Sinus rhythm. Right axis deviation. Peaked P waves in lead two.",
   echo:"Ejection fraction 60 percent. Right ventricle mildly dilated with elevated estimated pulmonary pressure.",
   bnp:"142 pg/mL", jvp:"7 mmHg",
   ferr:"210 ng/mL", iron:"104 mcg/dL", tsat:"34 percent",
   egfr:"78 mL/min/1.73 m2", usg:"1.022"
  }
},
{
  id:"F", who:"Alina P., 44", role:"dental hygienist",
  label:"Primary hyperaldosteronism from an aldosterone producing adenoma, with hypokalaemia and metabolic alkalosis",
  teach:"Renin angiotensin aldosterone axis, distal tubule potassium and hydrogen handling, resistant hypertension",
  beats:[
   "Blood pressure has stayed high on three medications. She has no symptoms she attributes to it.",
   "Craves salt. Drinks a lot of water and urinates often, including at night.",
   "No edema at all, which she thinks is strange given how much salt she eats.",
   "Occasional palpitations and a fluttering feeling after long shifts.",
   "Tingling around the mouth and in the fingers a few times a month.",
   "Muscle cramps and episodes of weakness in the legs, worse late in the week.",
   "No thyroid symptoms. No weight change. No striae or easy bruising.",
   "Cycles are regular and unchanged.",
   "Appetite normal. No vomiting, no diarrhea, no laxative or diuretic use.",
   "Color is normal. No pallor and no plethora.",
   "Blood pressure is markedly elevated in both arms with no dipping overnight.",
   "Bicarbonate is high and potassium is low on every panel taken.",
   "Breathing is normal at rest with no history of lung disease.",
   "Urine output is high and dilute. Urine potassium is high while serum potassium is low.",
   "Final visit. She wants to know why she is not swollen if she is retaining sodium."
  ],
  r:{
   hx_chief:"My blood pressure will not come down no matter what they put me on.",
   hx_time:"Hypertension for six years, resistant for the last two.",
   hx_meds:"Amlodipine, losartan, hydrochlorothiazide. No potassium supplement. No liquorice.",
   hx_diet:"Salts food heavily and craves it. Three liters of water daily.",
   hx_social:"Works four ten hour shifts. Sleeps seven hours. No tobacco.",
   hx_fam:"Mother with hypertension diagnosed in her thirties.",
   hx_ros:"Nocturia, muscle cramps, intermittent weakness, palpitations, perioral tingling. No edema.",
   vs_hr:"84 per minute, regular", vs_bp:"172 over 104 mmHg, equal in both arms",
   pe_edema:"No edema anywhere despite marked hypertension.",
   pe_card:"Regular. Fourth heart sound. No murmur.",
   na:"146 mEq/L", k:"2.8 mEq/L", cl:"96 mEq/L", hco3:"32 mEq/L", mg:"1.6 mg/dL",
   glu:"108 mg/dL", ca:"9.6 mg/dL",
   aldo:"34 ng/dL", renin:"0.2 ng/mL/hr", cort:"13.6 mcg/dL", acth:"24 pg/mL",
   ph:"7.49", pco2:"46 mmHg", abg_hco3:"33 mEq/L",
   ecg:"Sinus rhythm. Left ventricular hypertrophy. Flattened T waves with prominent U waves.",
   echo:"Ejection fraction 64 percent with concentric left ventricular hypertrophy.",
   map:"127 mmHg mean, pulse pressure 68 mmHg",
   amb:"Sustained elevation over 24 hours with absent nocturnal dipping.",
   uk:"52 mEq/day while serum potassium is 2.8 mEq/L", una:"142 mEq/L",
   uosm:"280 mOsm/kg", usg:"1.008", acr:"38 mg/g", egfr:"82 mL/min/1.73 m2",
   str:"4 of 5 in the proximal legs on a symptomatic day, 5 of 5 otherwise.",
   ck:"188 U/L", jvp:"6 mmHg"
  }
},
{
  id:"G", who:"Walter B., 58", role:"long haul driver",
  label:"Heart failure with reduced ejection fraction, with neurohormonal activation and dilutional hyponatraemia",
  teach:"Cardiac output, Starling forces, baroreflex, renin angiotensin aldosterone activation in a low output state",
  beats:[
   "Breathless lying flat. Sleeps on three pillows and wakes gasping about twice a week.",
   "Weight is up four kilograms in three weeks with no change in eating.",
   "Ankles swell through the day and are better by morning. Shoes no longer fit at night.",
   "Occasional irregular beats. He can feel them in his throat.",
   "Light headed if he stands too fast, but never fainted.",
   "Legs give out after a hundred meters. He says it is not the breath, it is the legs.",
   "No thyroid symptoms. Reports no temperature intolerance.",
   "Reduced libido for two years. He attributed it to the job.",
   "Appetite is poor and he feels full quickly. Abdomen feels tight.",
   "Color is normal but his hands are cool and his nail beds refill slowly.",
   "Blood pressure is low with a narrow pulse pressure. Neck veins are visibly distended at 45 degrees.",
   "Sodium has been low on every panel and he is not on a diuretic that would explain it.",
   "Crackles at both bases that do not clear with coughing.",
   "Urine output falls on the days he is most swollen. Urine sodium is very low.",
   "Final visit. He wants to know why his sodium is low if he is holding on to salt and water."
  ],
  r:{
   hx_chief:"I cannot lie flat and my legs swell up by the end of the day.",
   hx_time:"Twelve months, sharply worse in the last month.",
   hx_meds:"Lisinopril, metoprolol, furosemide taken irregularly.",
   hx_diet:"Truck stop food, very high salt. Two to three liters of fluid.",
   hx_social:"Drives ten to twelve hours a day. Former smoker. Minimal activity.",
   hx_fam:"Father died of a heart attack at 61.",
   hx_ros:"Orthopnoea, paroxysmal nocturnal dyspnoea, ankle swelling, early satiety, fatigue.",
   vs_hr:"96 per minute, irregular occasional ectopy", vs_bp:"102 over 76 mmHg",
   vs_rr:"20 per minute", vs_spo2:"93 percent", vs_wt:"Up 4 kg in three weeks",
   vs_ortho:"Systolic falls 16 mmHg on standing with minimal heart rate rise.",
   pe_skin:"Cool peripheries. Capillary refill three seconds.",
   pe_card:"Displaced apex. Third heart sound gallop. Jugular venous pressure elevated to the angle of the jaw at 45 degrees.",
   pe_lung:"Fine inspiratory crackles at both bases that do not clear with coughing.",
   pe_edema:"Two plus pitting edema to mid shin bilaterally.",
   pe_abd:"Mild tender hepatomegaly. No shifting dullness.",
   na:"130 mEq/L", k:"4.9 mEq/L", cl:"94 mEq/L", hco3:"26 mEq/L",
   bun:"38 mg/dL", cr:"1.6 mg/dL", alb:"3.4 g/dL", osm:"274 mOsm/kg",
   ecg:"Sinus rhythm with frequent ventricular ectopy. Left bundle branch block, QRS 152 ms.",
   echo:"Ejection fraction 28 percent. Dilated left ventricle. Moderate functional mitral regurgitation.",
   bnp:"1840 pg/mL", trop:"22 ng/L",
   map:"85 mmHg mean, pulse pressure 26 mmHg", jvp:"16 mmHg",
   cap:"Capillary hydrostatic 42 mmHg arterial end and 28 mmHg venous end. Plasma colloid osmotic 21 mmHg. Interstitial hydrostatic 1 mmHg. Interstitial colloid osmotic 4 mmHg.",
   aldo:"28 ng/dL", renin:"6.2 ng/mL/hr",
   una:"12 mEq/L", uosm:"640 mOsm/kg", usg:"1.026", acr:"64 mg/g", egfr:"46 mL/min/1.73 m2",
   hgb:"12.8 g/dL", hct:"38 percent", mcv:"90 fL",
   ph:"7.42", pco2:"33 mmHg", po2:"74 mmHg", abg_hco3:"22 mEq/L", lact:"2.4 mmol/L",
   walk:"180 meters, stopped for breathlessness, saturation 91 percent.",
   sexh:"Testosterone at the lower limit of the reference range."
  }
},
{
  id:"H", who:"Priya R., 29", role:"veterinary technician",
  label:"Primary adrenal insufficiency, autoimmune Addison disease, with mineralocorticoid and glucocorticoid deficiency",
  teach:"Adrenal axis, sodium and potassium handling, glucose regulation, why hyperpigmentation localises the lesion",
  beats:[
   "Exhausted in a way that sleep does not fix. Says she feels worst in the morning.",
   "Craving salt intensely. She has started eating olives and pickles straight from the jar.",
   "No swelling. Skin feels dry and she has lost six kilograms without trying.",
   "Heart races when she stands. Resting rate is in the low hundreds.",
   "Nearly fainted twice at work getting up from a crouch.",
   "Generalized weakness without any focal loss. Strength testing is only mildly reduced.",
   "Skin has darkened, most noticeably on the palm creases, knuckles, and an old scar.",
   "Periods have become irregular over the last eight months.",
   "Nausea most mornings, occasional vomiting, vague abdominal pain.",
   "Buccal mucosa shows patchy dark pigmentation.",
   "Blood pressure is low and drops further on standing.",
   "Sodium is low and potassium is high on every panel, with a mild low bicarbonate.",
   "Breathing is normal. She has no cough and no lung history.",
   "Urine sodium is inappropriately high for how depleted she is.",
   "Final visit. She wants to know why her skin darkened when the problem is in her adrenal glands."
  ],
  r:{
   hx_chief:"I am wiped out, I crave salt constantly, and I nearly passed out at work.",
   hx_time:"Six to eight months, worse in the last six weeks.",
   hx_meds:"None. No steroid use, past or present.",
   hx_diet:"Eating salty food constantly. Appetite otherwise poor. Nausea in the mornings.",
   hx_social:"Physical job on her feet. Sleeps eight hours and wakes unrefreshed.",
   hx_fam:"Mother with autoimmune thyroid disease. Cousin with type 1 diabetes.",
   hx_ros:"Fatigue, salt craving, weight loss, nausea, vomiting, dizziness on standing, darkening skin, irregular periods.",
   vs_hr:"106 per minute, regular", vs_bp:"94 over 58 mmHg", vs_temp:"36.4 C",
   vs_wt:"Down 6 kg in six months",
   vs_ortho:"Systolic falls 24 mmHg on standing with heart rate rising to 128.",
   pe_skin:"Diffuse hyperpigmentation, accentuated in the palmar creases, over the knuckles, and in an old appendectomy scar. Patchy pigmentation of the buccal mucosa. Reduced turgor.",
   pe_abd:"Mild diffuse tenderness without guarding.",
   na:"126 mEq/L", k:"5.8 mEq/L", cl:"94 mEq/L", hco3:"20 mEq/L",
   bun:"28 mg/dL", cr:"1.1 mg/dL", glu:"58 mg/dL", ca:"10.6 mg/dL", osm:"266 mOsm/kg",
   cort:"2.1 mcg/dL", acth:"486 pg/mL", aldo:"2 ng/dL", renin:"18.4 ng/mL/hr",
   tsh:"5.8 mIU/L", ft4:"1.0 ng/dL", tpo:"180 IU/mL", a1c:"4.4 percent", cpep:"0.9 ng/mL",
   wbc:"5.2 thousand/microliter with eosinophilia at 9 percent and relative lymphocytosis",
   hgb:"12.2 g/dL", hct:"37 percent", mcv:"91 fL",
   ecg:"Sinus tachycardia. Peaked T waves in leads V2 to V4.",
   una:"64 mEq/L despite clinical volume depletion", uosm:"340 mOsm/kg", usg:"1.014",
   egfr:"72 mL/min/1.73 m2",
   ph:"7.32", pco2:"36 mmHg", abg_hco3:"19 mEq/L",
   map:"70 mmHg mean, pulse pressure 36 mmHg", jvp:"2 mmHg",
   str:"4 plus of 5 globally without focal deficit.",
   cyc:"Cycles have become irregular over eight months with two missed periods.",
   lhfsh:"Follicle stimulating hormone 6.4 IU/L, luteinizing hormone 4.8 IU/L."
  }
}
];

module.exports = { COURSE, WEEKS, CATS, TESTS, NORMALS, VARIANTS };
